define(function(require) {
	var $ = require('jquery'),
		_ = require('underscore'),
		Backbone = require('backbone'),
		Marionette = require('marionette');

	var GroupModel = Backbone.Model.extend({
		defaults: {
			"isCanCreateComments": 1,
			"isCanEditOwnComments": 1,
			"isCanEditOwnCategoryComments": 0,
			"isCanEditAllComments": 0,
			"isCanDeleteOwnComments": 0,
			"isCanDeleteOwnCategoryComments": 0,
			"isCanDeleteAllComments": 0,
			"isCanCreateArticles": 1,
			"isCanEditOwnArticles": 1,
			"isCanEditOwnCategoryArticles": 0,
			"isCanEditAllArticles": 1,
			"isCanPublishOwnArticles": 0,
			"isCanPublishAllArticles": 0,
			"isCanDeleteOwnArticles": 1,
			"isCanDeleteOwnCategoryArticles": 0,
			"isCanDeleteAllArticles": 0,
			"isCanCreatePhotos": 1,
			"isCanEditOwnPhotos": 1,
			"isCanEditOwnCategoryPhotos": 0,
			"isCanEditAllPhotos": 1,
			"isCanPublishOwnPhotos": 0,
			"isCanPublishOwnCategoryPhotos": 0,
			"isCanPublishAllPhotos": 0,
			"isCanDeleteOwnPhotos": 1,
			"isCanDeleteOwnCategoryPhotos": 0,
			"isCanDeleteAllPhotos": 0,
			"isCanCreateForumThemes": 1,
			"isCanCreateForumPosts": 1,
			"isCanEditOwnForumThemes": 1,
			"isCanEditOwnCategoryForumThemes": 0,
			"isCanEditAllForumThemes": 0,
			"isCanEditOwnForumPosts": 1,
			"isCanEditOwnCategoryForumPosts": 0,
			"isCanEditAllForumPosts": 0,
			"isCanMoveOwnCategoryForumThemes": 0,
			"isCanMoveAllForumThemes": 0,
			"isCanDeleteOwnForumThemes": 0,
			"isCanDeleteOwnCategoryForumThemes": 0,
			"isCanDeleteAllForumThemes": 0,
			"isCanDeleteOwnForumPosts": 0,
			"isCanDeleteOwnCategoryForumPosts": 0,
			"isCanDeleteAllForumPosts": 0,
			"isCanCreateReputation": 1,
			"isCanEditReputation": 0,
			"isCanDeleteReputation": 0,
			"isCanDropReputation": 0,
			"isCanCreateBan": 0,
			"isCanEditBan": 0,
			"isCanDeleteBan": 0,
			"isCanCreatePrivateMessages": 1,
			"isCanCreateChatMessages": 1,
			"isCanDeleteOwnChatMessages": 0,
			"isCanDeleteAllChatMessages": 0,
			"isCanEditAllUserProfiles": 0,
			"isCanChangeAllUserGroups": 0,
			"isCanEditAllUserTitles": 0,
			"isCanGiveAwards": 0,
			"isCanRevokeAwards": 0,
			"name": "Гость"
		}
	});

	return GroupModel;
});